app/models.py
class Sources:
    '''
    Sources class that defines source objects
    '''

    def __init__(self, id, name, description, url, category, country):
        self.id = id
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.country = country


class Articles:
    '''
    Article class that defines the article objects
    '''

    def __init__(self, author, title, description, url, urlToImage):
        self.author = author
        self.title = title
        self.description = description
        self.url = url
        self.urlToImage = urlToImage

app/__init__.py
from flask import Flask

from config import config_options



def create_app(config_name):
    app = Flask(__name__)

    # Creating app configurations
    app.config.from_object(config_options[config_name])

    # Registering the BluePrint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting the config
    from .request import configure_request
    configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, error

app/main/views.py
from flask import render_template, redirect, url_for, request
from . import main
from ..models import Sources
from ..request import get_sources, get_articles


@main.route('/')
def index():

    # getting general news

    general_news = get_sources('general')
    business_news = get_sources('business')
    entertainment_news = get_sources('entertainment')
    sports_news = get_sources('sports')
    technology_news = get_sources('technology')
    science_news = get_sources('science')
    health_news = get_sources('health')


    title = 'Home-Best News Update Site'

    return render_template('index.html', title=title, General=general_news, Business=business_news,
                           Entertainment=entertainment_news, Sports=sports_news, Technology=technology_news,
                           Science=science_news, Health=health_news)


@main.route('/articles/<source_id>&<int:per_page>')
def articles(source_id, per_page):
    '''
    Function that returns articles based on their sources
    '''

    news_source = get_articles(source_id, per_page)
    title = f'{source_id} | All Articles'
    return render_template('articles.html', title=title, name=source_id, news=news_source)

app/templates/articles.html
{% extends 'base.html' %} {% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 heading">
            <h1> {{name}} </h1>
        </div>
    </div>
    <div class="row">
        {% for article in news %}
        <div class="col-sm-6">
            <div class="img-box mb-4">
                <a href={{article.url}} target="_blank">
                    <img class="thumbnail img-el img-fluid" src={{article.urlToImage}} alt="IMAGE LOADING...">
                </a>
            </div>
            <div class="words">
                <h4 class="text-bold"> {{article.title}} </h4>
                <p>Posted by
                    <span class="text-muted date-author">{{article.author}}</span>
                    on
                    <span class="text-muted date-author">{{article.publishedAt}}</span>
                </p>
                <p> {{article.description}}...
                    <a href={{article.url}} target="_blank"><button type="button" class="btn btn-outline-primary">Read more</button></a>
                </p>
                <hr>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"> {% endblock%}

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}


<!-- Content block -->
{% block content %}
    <div class="container-fluid">

            <!-- general news -->
            <h3> General news</h3>
            <div class="row">
                {{ macro.displayNews(General)}}
            </div>
                
                <hr>
            <!---Business news-->
            <h3> Business news</h3>
            <div class="row">
                {{ macro.displayNews(Business)}}                
            </div>

            <!--Entertainment news-->
            <h3> Entertainment news</h3>
            <div class="row">
                {{ macro.displayNews(Entertainment)}}
            </div>
<hr>
            <!---sports news-->
            <h3> Sports news</h3>
            <div class="row">
                {{ macro.displayNews(Sports)}}
            </div>
<hr>
            <!---Technology news--->
            <h3> Technology news</h3>
            <div class="row">
                {{ macro.displayNews(Technology)}}
            </div>
<hr>            
            <!--Science news-->
            <h3> Science news</h3>
            <div class="row">
                {{ macro.displayNews(Science)}}
            </div>
<hr>
            <!---Health news--->
            <h3> Health news</h3>
            <div class="row">
                {{ macro.displayNews(Health)}}
            </div>

    </div>
{% endblock%}

app/templates/macros.html
{% macro displayNews(category) %} {% for category in category %}
<div class="card border-primary mb-3 col-md-3">
    <div class="card-header">{{category.name}}</div>
    <div class="card-body">
        <p class="card-text">{{category.description|truncate(150)}}
            <br>
            <a href="/articles/{{category.id}}&40"><button type="button" class="btn btn-primary btn-sm">Read Articles</button></a></p>
    </div>
</div>

{% endfor %} {% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">News-Highlights</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.articles',source_id = 'abc-news',per_page='10')}}">News</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/templates/topheadlines.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 heading">
            <h1> {{name}} </h1>
        </div>
    </div>
    <div class="row">
        {% for article in news %}
        <div class="col-md-3 articles-details">
            <a href={{article.url}} target="_blank">
                <img src={{article.urlToImage}} alt="IMAGE LOADING...">
            </a>
            <div class="words">
                <h4 class="text-bold"> {{article.title}} </h4>
                <p class="small">- {{article.author}} </p>
                <p class="small">Posted on {{article.publishedAt}}</p>
                <hr>
                <p> {{article.description}}...
                    <a href={{article.url}} target="_blank">Read More</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}